language: java
jdk:
- oraclejdk7
notifications:
  email:
  - haroon_sheikh@hotmail.co.uk
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy
  -DskipTests --settings settings.xml"
env:
  matrix:
  - secure: AV2sOUVOIIpLQhgK0yT+ZnRuixUXy4hKGutD0hJ162YUpjOUjtk9fvCxRMCyeOMgRAIgj2om2XPluz0xbKTh3r4f0IK7DKtR7NE+tP8LZTh+LHVT42q6CWkMqhIB1ubd+WSLAUOZ+2IVCNlANHn9qeJKlXT0/oyWdlEH/nHr3/VBn9hbgxylI3A7d4e4ARDmzHAH3qPpHBqCYgb7TbHkg/bEeOjzAYKTDVae4S2hTje7sbOjMSthoVV9wejeNuGcYiRk89Qt8c3mbH6ShwQjOlWd52JIwK4trb3HW6TvN8qdx/sdSY/SSsuDib263EHTQts67hZ0afeeF45u1bpKYcRgUbV1r7YRR+84Tbrt4vdGXRi8r9MS4Gr4Rdt6EoFaTI7rfCn9jrXSjizWmXeayXUG0tdoOUzZoUhmkWDYfEPpe3HvuhoNxbH6G5la3q6NVzj5+SjZc/Fwaz8rTtXjmtxKbpRCLaEwFX0bTDL0sX4V6ELHPjwsyAmLfZvU+7GHh82fJHTXG1gV2R/8W6ox16p8IdlM0jo7m5xnjfzU+cyj4+T95ic0+4LuxD4bAC9cJUUJN6TKYmJwwRM0K8zWo47JbF5zxkvFseBX+0ggRG2W7AcBHDLOweupy9y93fQDpTQ6oj0Vat9ZSWvI7AdttEN4t69Gn8xH54wOT6fQK/0=
  - secure: J6sg9dxBHbbdGAYP3aFgKuoH9avQDFNk3FGedwKw3vVrVWqkbmWSWINC6iS9azO+tq4wGVygbCgf2jT6n+RiFakBDfCE4u2ps1pnYyt4fZiPpJzmhRnrKb7G7bkmHrBiSXbOngXoddBhaV2rC8xZIHXChdXrRbha83/MACQvsDizTtGVxkuY2WSWVnNUv6Ded4XRCJbVNGy1wBilHqBWRwSt5v9BRRxnDYNSV26zO4K2rs+Wgax48kNGaAsYgLP+9J8TUks7vT+AuSL818t3YHYMyhtT7Dpx4mACKpt2l3ZLEGgL1/hdLqahGxVgrtkJ2gEDLUuksQuhoj2gPYoW5gt3qFlTloIIgIX0lEdC+xqtiN1eQ81NjTovALGh0E1QqOqfolwGRGZbONo7xtkbvY9UE1lQRxhm9+FGmwAZL0YN9cYE7liurvnLLCEbOSSNiW47ncAsd/RV9MqYuBCz4D6w4y4Z7xfyDsv1OaWqwMWx0KDbxVEeuU4CmY9zmAtyQsN5xKX84fmYi1CXeo7dyKXw6iEEY5Drfx5/XqI6r6iHiUN7ZEvDk3Xu9cbzwc6xFTogdypsF5WclvF2XTYNmf/q9wMcD4ibOrenABJS+u/i0UGGuGoD75hsGPQX83YEgqV9ZBqf1gy8e/XgWhRUNGZIWKa9U6tsH+c54vzPUmQ=
